name: Continuous Delivery

on:
  push:
    branches: main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: build and push
          run: |
            docker build -t almeidacra/java-ping-aula31205-dbre .
            docker push almeidacra/java-ping-aula31205-dbre